version: '3.8'

services:
  postgres:
    container_name: db_postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: catering_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
