services:
  postgres:
    container_name: db_postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: catering_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"
    restart: unless-stopped

  seq:
    image: datalust/seq:2023.1
    container_name: seq
    ports:
      - "8080:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    restart: unless-stopped
    mem_limit: 4g
    memswap_limit: 4g
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  seq-data:
